---
- hosts: target
  become: true
  tasks:
  - name: 'install kernel updates'
    yum:
      name: 'kernel'
      state: 'latest'

 - name: 'install other updates'
    yum:
#     disablerepo: '*'
      enablerepo: 'epel,ol7_latest'
      name: '*'
      state: 'latest'
      ignore_errors: yes
